---
- name: configure all devices
  hosts: routers
  gather_facts: no
  
  tasks:
    - name: configure banners
      include_role:
        name: banner
  
    - name: configure ACLs
      include_role:
        name: acl
        
    - name: configure L3 interfaces
      include_role:
        name: l3_interface
