---
- name: Parse ACL
  cisco.ios.ios_acls:
    state: merged
    running_config: "{{ acl_config }}" #Found in host_vars/{{device}}.yml
    config:
    - afi: ipv4
      acls:
      - name: 
- name: debug ACL
  ansible.builtin.debug:
    var: ios_acl
    
    
#- name: Configure ACL
#  cisco.ios.ios_acls:
#    state: merged
#    config: "{{ ios_acl.parsed }}" 
