---
- name: Configure ACL
  cisco.ios.ios_acls:
    state: merged
    config: "{{ acl_config }}"
            
  
#- name: debug ACL
#  ansible.builtin.debug:
#    var: ios_acl
    
    
#- name: Configure ACL
#  cisco.ios.ios_acls:
#    state: merged
#    config: "{{ ios_acl.parsed }}" 
